# -*- coding: utf-8 -*-
"""Wk11.LearningLog.RussellPetersen.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-pZy-RPxPNMhwLK_qUt6-7xKBy_1pcc-
"""

import pandas as pd
import numpy as np
df = pd.read_csv("/content/stats.csv")

"""What is the most effective arsenal to have in the major leagues? Grouping pitchers by arsenal into categories, and then comparing xwOBA, K%-BB%, and Whiff%. To find all of this information I used Baseball Savant, a very helpful baseball statistics website to compile data. The CSV file I downloaded off of the website has all of the statistics that I will be working with."""

df.head()

# Sort the dataset by batters faced
df = df.sort_values(by=['pa'], ascending=False)
df.head()

"""# Data Audit
This data set was created by myself to study the relationships between pitch arsenals and important statistical indicators of a baseball pitchers success. This is a sample of all pitchers in the 2025 season who threw at least 100 innings, limiting the sample to only be of starting pitchers. This data is collected from the 2025 season, and is straight from the MLB website.

# Initial Analysis
"""

# Find the mean, median and outliers for kk%-bb%, xWOBA.
# Calculate k_percent - bb_percent
df['k_minus_bb_percent'] = df['k_percent'] - df['bb_percent']

# Columns for analysis
analysis_cols = ['k_minus_bb_percent', 'xwoba']

# For each column, find mean, median, and outliers
results = {}
for col in analysis_cols:
    mean_val = df[col].mean()
    median_val = df[col].median()

    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1

    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    outliers = df[(df[col] < lower_bound) | (df[col] > upper_bound)][['last_name, first_name', col]]

    results[col] = {
        'mean': mean_val,
        'median': median_val,
        'outliers': outliers.to_dict(orient='records')
    }

print("Analysis Results:")
for col, data in results.items():
    print(f"\n--- {col} ---")
    print(f"Mean: {data['mean']:.2f}")
    print(f"Median: {data['median']:.2f}")
    print(f"Outliers ({len(data['outliers'])} found):")
    if data['outliers']:
        for outlier in data['outliers']:
            print(f"  {outlier['last_name, first_name']}: {outlier[col]:.2f}")

"""# Data Cleaning
The major data wranlging/cleaning that needs to be done to this data set is grouping the pitchers based on pitch usage to determing their arsenal. From there I will be able to run analysis and formulate relationships based on pitch usage and success.

# Week 12 Update: Interactive Visualization
"""

import plotly.express as px
import plotly.io as pio

# 3 Dimensional Scatter Plot
fig = px.scatter_3d(
    df,
    x='xwoba',
    y='k_minus_bb_percent',
    z='exit_velocity_avg',
    color='k_minus_bb_percent',
    size_max=10,
    hover_name='last_name, first_name',
    hover_data=['xwoba', 'k_minus_bb_percent', 'exit_velocity_avg', 'pa'],
    title='Top 100 Starting Pitchers of 2025',
    labels={
        'xwoba': 'xWOBA',
        'k_minus_bb_percent': 'K - BB Rate',
        'exit_velocity_avg': 'Average Exit Velo'
    }
)

fig.update_layout(scene_camera=dict(eye=dict(x=1.8, y=1.8, z=0.8)))
fig.show()